# Generated by Django 4.0 on 2021-12-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
